[package]
name = "backlinks-init"
version = "0.1.0"
edition = "2021"

[dependencies]
walkdir = "2"
regex = "1"
clap = { version = "4", features = ["derive"] }
rayon = "1"

[profile.release]
opt-level = 3
lto = true
